listeners:
  client:
    protocol: 'PLAINTEXT'
  controller:
    protocol: 'PLAINTEXT'
  external:
    protocol: 'PLAINTEXT'
  interbroker:
    protocol: 'PLAINTEXT'

externalAccess:
  enabled: true
  controller:
    service:
      type: NodePort
  broker:
    service:
      type: NodePort
  autoDiscovery:
    enabled: true
serviceAccount:
  create: true
rbac:
  create: true
controller:
  automountServiceAccountToken: true
broker:
  automountServiceAccountToken: true