apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: "{{ .Values.app.image }}:{{ .Values.app.tag }}"
          imagePullPolicy: Always
          lifecycle:
            postStart:
              exec:
                command: ['/bin/sh', '-c', 'composer install --no-dev']
          volumeMounts:
            - name: app-auth-env-config
              mountPath: '/var/www/.env.local'
              subPath: '.env.local'
            - name: app-auth-cache-volume
              mountPath: '/var/www/var/'

        - name: {{ .Values.nginx.name }}
          image: {{ .Values.nginx.image }}
          ports:
            - name: {{ .Values.nginx.portName }}
              containerPort: {{ .Values.nginx.port }}
          volumeMounts:
            - name: nginx-config
              mountPath: '/etc/nginx/conf.d'

      volumes:
        - name: app-auth-cache-volume
          emptyDir: {}
        - name: app-auth-env-config
          configMap:
            name: {{ .Values.app.name }}-config-map
        - name: nginx-config
          configMap:
            name: {{ .Values.nginx.name }}-config-map
