apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.name }}-config-map
data:
  .env.local: |
    APP_ENV=prod
    APP_SECRET={{ .Values.app.appSecret }}

    REDIS_HOST={{ printf "app-redis-master.%s.svc.cluster.local" .Release.Namespace }}
    REDIS_PORT={{ .Values.app.redis.port }}
    REDIS_PASSWORD={{ .Values.app.redis.password }}
    REDIS_DB={{ .Values.app.redis.db }}
    KAFKA_BROKER_LIST="app-kafka.app.svc.cluster.local:9092"

    ADV_MIN_LENGTH=30
