framework:
  http_client:
    default_options:
      http_version: '2.0'
    scoped_clients:
      app.user.client:
        base_uri: '%env(APP_USER_HOST)%'
        headers:
          Content-Type: 'application/json'