apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.name }}-config-map
data:
  .env.local: |
    APP_ENV=prod
    APP_SECRET={{ .Values.app.appSecret }}
    JWT_SECRET={{ .Values.app.appSecret }}
    SERVICE_TOKEN={{ .Values.app.appSecret }}
    DATABASE_URL={{ printf "postgresql://%s:%s@app-db-postgresql.%s.svc.cluster.local:%s/%s?serverVersion=16&charset=utf8"
      .Values.app.postgresql.username
      .Values.app.postgresql.password
      .Release.Namespace
      .Values.app.postgresql.port
      .Values.app.postgresql.db }}
    KAFKA_BROKER_LIST="app-kafka.app.svc.cluster.local:9092"
    APP_USER_HOST={{ .Values.app.userHost }}