apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-service
  labels:
    app: {{ .Values.app.name }}-service
spec:
  selector:
    app: {{ .Values.app.name }}
  ports:
    {{- range .Values.service.ports }}
    - port: {{ .port }}
      protocol: TCP
      targetPort: {{ .targetPort }}
    {{- end}}
  type: {{ .Values.service.type }}
