{
 "title": "App dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Latency GET-adv_get_all ms.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(app_adv_request_durations_histogram_seconds_bucket{action=\"GET-adv_get_all\"}[1m])))",
     "legendFormat": "0.5 квантиль"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(app_adv_request_durations_histogram_seconds_bucket{action=\"GET-adv_get_all\"}[1m])))",
     "legendFormat": "0.95 квантиль"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(app_adv_request_durations_histogram_seconds_bucket{action=\"GET-adv_get_all\"}[1m])))",
     "legendFormat": "0.99 квантиль"
    },
    {
     "expr": "histogram_quantile(1, sum by(le) (rate(app_adv_request_durations_histogram_seconds_bucket{action=\"GET-adv_get_all\"}[1m])))",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(app_adv_http_requests_total{action!=\"all\"}[1m])) by(action)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error rate 4XX",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(app_adv_http_4xx_responses_total{action!=\"all\"}[1m])) by(action)",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Error rate 5XX",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(app_adv_http_5xx_responses_total{action!=\"all\"}[1m])) by(action)",
     "legendFormat": "{{action}}"
    }
   ]
  }
 ]
}