app:
  name: app-billing
  replicaCount: 3
  image: ygomonov/otus-app-billing
  tag: hw08
  appSecret: f975d3f7d9081bc041a6bd9d66175e38
  postgresql:
    username: "user"
    password: "!ChangeMe!"
    port: "5432"
    db: app-billing
  redis:
    port: 6379
    password: "redis-pass"
    session_db: 10
  portName: app-bill-port
  port: 8003

service:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: app-bill-port

ingress:
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/auth-url: "http://app-auth-service.app.svc.cluster.local/api/v1/auth"
    nginx.ingress.kubernetes.io/auth-response-headers: "X-Auth-Token"
  hosts:
    - host: arch.homework
      paths:
        - path: /app-billing(/|$)(.*)
          pathType: ImplementationSpecific
          port: 80

migrationJob:
  backoffLimit: 5
  ttlSecondsAfterFinished: 60
