apiVersion: batch/v1
kind: Job
metadata:
  name: job-migration
spec:
  template:
    spec:
      containers:
        - name: job-migration
          imagePullPolicy: Always
          image: ygomonov/otus-microservice-architecture:hw04
          command: [ '/bin/sh', '-c', 'bin/console d:m:m' ]
          env:
            - name: APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: app_secret
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: dsn
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: app-config-map
                  key: app_env
      restartPolicy: Never
  backoffLimit: 10
  ttlSecondsAfterFinished: 60