account_get:
    path: /api/v1/account/{userId<\d+>}
    controller: App\UI\Account\Controller\Get\Controller
    methods: GET

account_top_up:
    path: /api/v1/account/top-up/{userId<\d+>}
    controller: App\UI\Account\Controller\TopUp\Controller
    methods: PUT

account_pay:
    path: /api/v1/account/pay/{userId<\d+>}
    controller: App\UI\Account\Controller\Pay\Controller
    methods: PUT

account_rollback_pay:
    path: /api/v1/account/rollback/{userId<\d+>}
    controller: App\UI\Account\Controller\Rollback\Controller
    methods: PUT

account_uuid:
    path: /api/v1/account/uuid
    controller: App\UI\Uuid\Controller\Get\Controller
    methods: GET

healthcheck:
    path: /health
    controller: App\UI\HealthCheck\Controller
    methods: GET