{
 "title": "App dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Latency POST-user_create, ms.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(app_request_durations_histogram_seconds_bucket{action=\"POST-user_create\"}[1m])))",
     "legendFormat": "0.5 квантиль"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(app_request_durations_histogram_seconds_bucket{action=\"POST-user_create\"}[1m])))",
     "legendFormat": "0.95 квантиль"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(app_request_durations_histogram_seconds_bucket{action=\"POST-user_create\"}[1m])))",
     "legendFormat": "0.99 квантиль"
    },
    {
     "expr": "histogram_quantile(1, sum by(le) (rate(app_request_durations_histogram_seconds_bucket{action=\"POST-user_create\"}[1m])))",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Latency GET-user_get, ms.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(app_request_durations_histogram_seconds_bucket{action=\"GET-user_get\"}[1m])))",
     "legendFormat": "0.5 квантиль"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(app_request_durations_histogram_seconds_bucket{action=\"GET-user_get\"}[1m])))",
     "legendFormat": "0.95 квантиль"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(app_request_durations_histogram_seconds_bucket{action=\"GET-user_get\"}[1m])))",
     "legendFormat": "0.99 квантиль"
    },
    {
     "expr": "histogram_quantile(1, sum by(le) (rate(app_request_durations_histogram_seconds_bucket{action=\"GET-user_get\"}[1m])))",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Latency PUT-user_update, ms.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(app_request_durations_histogram_seconds_bucket{action=\"PUT-user_update\"}[1m])))",
     "legendFormat": "0.5 квантиль"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(app_request_durations_histogram_seconds_bucket{action=\"PUT-user_update\"}[1m])))",
     "legendFormat": "0.95 квантиль"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(app_request_durations_histogram_seconds_bucket{action=\"PUT-user_update\"}[1m])))",
     "legendFormat": "0.99 квантиль"
    },
    {
     "expr": "histogram_quantile(1, sum by(le) (rate(app_request_durations_histogram_seconds_bucket{action=\"PUT-user_update\"}[1m])))",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Latency DELETE-user_delete, ms.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(app_request_durations_histogram_seconds_bucket{action=\"DELETE-user_delete\"}[1m])))",
     "legendFormat": "0.5 квантиль"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(app_request_durations_histogram_seconds_bucket{action=\"DELETE-user_delete\"}[1m])))",
     "legendFormat": "0.95 квантиль"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(app_request_durations_histogram_seconds_bucket{action=\"DELETE-user_delete\"}[1m])))",
     "legendFormat": "0.99 квантиль"
    },
    {
     "expr": "histogram_quantile(1, sum by(le) (rate(app_request_durations_histogram_seconds_bucket{action=\"DELETE-user_delete\"}[1m])))",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(app_http_requests_total{action!=\"all\"}[1m])) by(action)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error rate 5XX",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(app_http_5xx_responses_total{action!=\"all\"}[1m])) by(action)",
     "legendFormat": "{{action}}"
    }
   ]
  }
 ]
}