{
 "title": "Ingress dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Latency POST-user_create, ms.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{method=\"POST\"}[1m])))",
     "legendFormat": "0.5 квантиль"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{method=\"POST\"}[1m])))",
     "legendFormat": "0.95 квантиль"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{method=\"POST\"}[1m])))",
     "legendFormat": "0.99 квантиль"
    },
    {
     "expr": "histogram_quantile(1, sum by(le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{method=\"POST\"}[1m])))",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Latency GET-user_get, ms.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{method=\"GET\"}[1m])))",
     "legendFormat": "0.5 квантиль"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{method=\"GET\"}[1m])))",
     "legendFormat": "0.95 квантиль"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{method=\"GET\"}[1m])))",
     "legendFormat": "0.99 квантиль"
    },
    {
     "expr": "histogram_quantile(1, sum by(le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{method=\"GET\"}[1m])))",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Latency PUT-user_update, ms.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{method=\"PUT\"}[1m])))",
     "legendFormat": "0.5 квантиль"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{method=\"PUT\"}[1m])))",
     "legendFormat": "0.95 квантиль"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{method=\"PUT\"}[1m])))",
     "legendFormat": "0.99 квантиль"
    },
    {
     "expr": "histogram_quantile(1, sum by(le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{method=\"PUT\"}[1m])))",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Latency DELETE-user_delete, ms.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{method=\"DELETE\"}[1m])))",
     "legendFormat": "0.5 квантиль"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{method=\"DELETE\"}[1m])))",
     "legendFormat": "0.95 квантиль"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{method=\"DELETE\"}[1m])))",
     "legendFormat": "0.99 квантиль"
    },
    {
     "expr": "histogram_quantile(1, sum by(le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{method=\"DELETE\"}[1m])))",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests[1m])) by(method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error rate 5XX",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by(method) (rate(nginx_ingress_controller_requests{status=~\"^5.*$\"}[1m]))",
     "legendFormat": "{{action}}"
    }
   ]
  }
 ]
}