app:
  name: app-auth
  replicaCount: 1
  image: ygomonov/otus-app-auth
  tag: hw06
  appSecret: f975d3f7d9081bc041a6bd9d66175e38
  postgresql:
    username: "user"
    password: "!ChangeMe!"
    port: "5432"
    db: app-user
  redis:
    port: 6379
    password: "redis-pass"
    session_db: 10

nginx:
  name: app-auth-nginx
  image: nginx:latest
  portName: nginx-port
  port: 80

service:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: nginx-port

ingress:
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - host: arch.homework
      paths:
        - path: /app-auth(/|$)(.*)
          pathType: ImplementationSpecific
          port: 80

migrationJob:
  restartPolicy: Never
  backoffLimit: 5
  ttlSecondsAfterFinished: 60
