# Пользователь
user_create:
    path: /api/v1/user/create
    controller: App\UI\User\Controller\Create\Controller
    methods: POST

user_get:
    path: /api/v1/user/{userId<\d+>}
    controller: App\UI\User\Controller\Get\Controller
    methods: GET
    
user_delete:
    path: /api/v1/user/{userId<\d+>}
    controller: App\UI\User\Controller\Delete\Controller
    methods: DELETE
    
user_update:
    path: /api/v1/user/{userId<\d+>}
    controller: App\UI\User\Controller\Update\Controller
    methods: PUT